### PR TITLE
Feature/lasers and stuff

### PR DESCRIPTION
**Pull request by ZweatMonash**
Added rover model with 2D lidar with 360 degrees of range. Would be useful to have another configuration to test navigation algorithms. Made it to work with the bug motion path planning algorithm in the autonomous repo.

### CODE REVIEW

**Comment by JmcRobbie** [comment]
Screenshot from 2020-01-25 22-17-34
I think Im having a bit of trouble getting it to work properly? Or is this nominal? Looks like an awesome contribution, just needs a bit of an explainer in the readme, I'm not sure how im supposed to use this tool! 

> Made it to work with the bug motion path planning algorithm in the autonomous repo.

Would also appreciate an explainer as to how you did this :P 

Happy to merge it after these questions are all covered.

**Comment by JmcRobbie** [comment]
Nevermind I was launching the wrong world lol. 
Screenshot from 2020-01-25 22-23-39

Just add an explainer to the readme covering how to switch between models with the 2d lidar and the 3d lidar then should be good to merge. Nice work :)

**Review by JmcRobbie — CHANGES_REQUESTED** [review]
Add some readme explanation or at least link to accompanying documentation so other people know how to use it. Otherwise great.

**Comment by ZweatMonash** [comment]
> 
> > Made it to work with the bug motion path planning algorithm in the autonomous repo.
> 
> Would also appreciate an explainer as to how you did this :P

Its in the novarover/autonomous repo feature/bug2 branch's README  but I also wrote something short in this readme and added a few more instructions to switch worlds and models. Let me know if you think it needs something more.

**Comment by ZweatMonash** [comment]
https://github.com/novarover/autonomous/tree/feature/bug2 <-- its here. Should I create a pull request for this branch as well?

**Review by JmcRobbie — APPROVED** [review]

**Comment by JmcRobbie** [comment]
> https://github.com/novarover/autonomous/tree/feature/bug2 <-- its here. Should I create a pull request for this branch as well?

I think that'd be a good idea, be sure to rebase ontop of Craigs latest changes and deal with the merge errors you are going to have. 
git checkout feature/bug2
git rebase develop
It'll have some merge errors that youll have to deal with I think. Then open a PR, the bug2 motion control looks great, might just use it in place of a custom solution for motion planning and obstacle avoidance.

**Pull request merged**
