### PR TITLE
Feature/utah terrain

### PR DESCRIPTION
**Pull request by craigreid42**
- utah terrain added to competition world
 - improvements to model including suspension and torque so it is able to climb slopes without slipping

### CODE REVIEW

**Comment by craigreid42** [comment]
Screenshot from 2020-02-10 15-25-13

**Comment by craigreid42** [comment]
Screenshot from 2020-02-10 15-19-39

**Comment by craigreid42** [comment]
There's too much grass for a desert, but I am yet to figure out how to change the texture. 
I tried changing the lines: 
```
              <texture>
                <diffuse>file://media/materials/textures/dirt_diffusespecular.png</diffuse>
                <normal>file://media/materials/textures/flat_normal.png</normal>
                <size>1</size>
              </texture>
              <texture>
                <diffuse>file://media/materials/textures/grass_diffusespecular.png</diffuse>
                <normal>file://media/materials/textures/flat_normal.png</normal>
                <size>1</size>
              </texture>
              <texture>
                <diffuse>file://media/materials/textures/fungus_diffusespecular.png</diffuse>
                <normal>file://media/materials/textures/flat_normal.png</normal>
                <size>1</size>
              </texture>
              <blend>
                <min_height>2</min_height>
                <fade_dist>5</fade_dist>
              </blend>
              <blend>
                <min_height>4</min_height>
                <fade_dist>5</fade_dist>
              </blend>
```
I think this is good enough for now.

**Comment by craigreid42** [comment]
I was having this issue which led me to delete the texture values because I thought they were not used. http://answers.gazebosim.org/question/17829/heightmap-not-updating-in-gazebo-8-after-changing-world-file/

**Review by JmcRobbie — CHANGES_REQUESTED** [review]
Changes requested:
* Way of addressing the caching issue causing textures to not be loaded.

**Comment by craigreid42** [comment]
Since that file won't be changed that often, I think a comment to delete `~/.gazebo/paging` should be enough. Can you confirm @JmcRobbie that this now works on your machine after pulling this branch?

**Review by JmcRobbie — APPROVED** [review]
Looks good, runs fine on my system. Nice work.

**Pull request merged**
